// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Camera struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Photo struct {
	Link   string  `json:"link"`
	Camera *Camera `json:"camera"`
	Rover  *Rover  `json:"rover"`
	Date   string  `json:"date"`
}

type Rover struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
